"""
Django settings for censoProject project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os.path
from pathlib import Path
import redis
from decouple import config, Csv

from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ==============================================================================
# SECURITY SETTINGS
# ==============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())

# ==============================================================================
# HTTPS/SSL SECURITY SETTINGS
# ==============================================================================

if not DEBUG:
    # Forzar HTTPS en producción
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=True, cast=bool)
    CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=True, cast=bool)

    # HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000, cast=int)  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Seguridad adicional
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

    # Proxy settings para servidores detrás de balanceador
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
else:
    # En desarrollo, estas configuraciones están desactivadas
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0

# ==============================================================================
# SESSION SECURITY
# ==============================================================================

SESSION_COOKIE_AGE = config('SESSION_COOKIE_AGE', default=86400, cast=int)  # 24 horas
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = config('SESSION_EXPIRE_AT_BROWSER_CLOSE', default=True, cast=bool)
SESSION_COOKIE_HTTPONLY = True  # No accesible desde JavaScript
SESSION_COOKIE_SAMESITE = 'Lax'  # Protección CSRF adicional

# CSRF Security
CSRF_COOKIE_HTTPONLY = False  # Debe ser False para que Django pueda leerla
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_USE_SESSIONS = False

# ==============================================================================
# DATA ENCRYPTION
# ==============================================================================

# Clave para encriptar datos sensibles (números de identificación, etc.)
DATA_ENCRYPTION_KEY = config('DATA_ENCRYPTION_KEY', default='')

# URL del sitio (para códigos QR y verificación de documentos)
SITE_URL = config('SITE_URL', default='http://127.0.0.1:8000')

MESSAGE_STORAGE = "django.contrib.messages.storage.cookie.CookieStorage"

SITE_ID = 1

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'rest_framework',
    # 'rest_framework_simplejwt',  # COMENTADO: No instalado
    # 'rest_framework_simplejwt.token_blacklist',  # COMENTADO: No instalado
    "corsheaders",
    'coreapi',
    "crispy_forms",
    "crispy_bootstrap5",
    'censoapp',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'formtools',
    'simple_history',
    # Seguridad
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',  # 2FA Middleware
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
    'simple_history.middleware.HistoryRequestMiddleware',
    'censoapp.middleware.OrganizationFilterMiddleware',  # Multi-organizacion
]


ROOT_URLCONF = 'censoProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        # 'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # `allauth` needs this from django
                'django.template.context_processors.request',
            ],
        },
    },

]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# ==============================================================================
# DJANGO-ALLAUTH CONFIGURATION (Django-allauth v65.14.1)
# ==============================================================================

# Verificación de email
ACCOUNT_EMAIL_VERIFICATION = config('ACCOUNT_EMAIL_VERIFICATION', default='optional')
ACCOUNT_UNIQUE_EMAIL = True

# Métodos de autenticación (nueva sintaxis)
ACCOUNT_LOGIN_METHODS = {'email', 'username'}

# Campos requeridos en el signup (nueva sintaxis)
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']

# Rate Limiting (nueva sintaxis)
ACCOUNT_RATE_LIMITS = {
    'login_failed': '5/5m',  # 5 intentos fallidos en 5 minutos
    'confirm_email': '1/3m',  # 1 confirmación de email cada 3 minutos
    'manage_email': '10/1h',  # 10 cambios de email por hora
    'change_password': '5/5m',  # 5 cambios de contraseña cada 5 minutos
    'reset_password': '5/30m',  # 5 resets de contraseña cada 30 minutos
    'reset_password_from_key': '20/1d',  # 20 resets con token por día
    'reauthenticate': '10/5m',  # 10 reautenticaciones cada 5 minutos
    'signup': '20/1h',  # 20 registros por hora por IP
}

# Seguridad de contraseñas
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = False
ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_SESSION_REMEMBER = True

# Redirecciones
ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS = True
LOGIN_REDIRECT_URL = reverse_lazy('home')
ACCOUNT_LOGOUT_REDIRECT_URL = '/accounts/login/'

# Cambio de email
ACCOUNT_CHANGE_EMAIL = True
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3

# Plantillas de email personalizadas
ACCOUNT_EMAIL_SUBJECT_PREFIX = '[Censo Web] '

WSGI_APPLICATION = 'censoProject.wsgi.application'


# Database
# Usar MySQL en producción (DEBUG=False) y SQLite en desarrollo (DEBUG=True)
if DEBUG:
    # SQLite para desarrollo local
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.censo_Web',
            'ATOMIC_REQUESTS': True,
        }
    }
else:
    # MySQL para producción (PythonAnywhere)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST'),
            'PORT': config('DB_PORT', default='3306'),
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                'charset': 'utf8mb4',
            },
            'ATOMIC_REQUESTS': True,
        }
    }



# Cache Configuration with Redis (or fallback to local memory)
# https://docs.djangoproject.com/en/4.2/topics/cache/
try:
    # Intentar usar Redis si está disponible
    # Verificar que Redis esté corriendo
    redis_host = config('REDIS_HOST', default='127.0.0.1')
    redis_port = config('REDIS_PORT', default=6379, cast=int)
    redis_db = config('REDIS_DB', default=1, cast=int)

    try:
        r = redis.Redis(host=redis_host, port=redis_port, db=redis_db, socket_connect_timeout=1)
        r.ping()
        REDIS_AVAILABLE = True
    except (redis.ConnectionError, redis.TimeoutError):
        REDIS_AVAILABLE = False

    if REDIS_AVAILABLE:
        CACHES = {
            'default': {
                'BACKEND': 'django_redis.cache.RedisCache',
                'LOCATION': f'redis://{redis_host}:{redis_port}/{redis_db}',
                'OPTIONS': {
                    'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                    'SOCKET_CONNECT_TIMEOUT': 5,
                    'SOCKET_TIMEOUT': 5,
                    'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
                    'CONNECTION_POOL_KWARGS': {
                        'max_connections': 50,
                        'retry_on_timeout': True,
                    },
                    'IGNORE_EXCEPTIONS': True,  # Fallback to database if Redis fails
                },
                'KEY_PREFIX': 'censo',
                'TIMEOUT': 300,  # 5 minutos por defecto
            }
        }
        import sys
        sys.stderr.write("OK: Redis conectado. Usando cache de Redis.\n")

        # Solo usar sesiones en Redis si está disponible y funcionando
        # SESSION_ENGINE = "django.contrib.sessions.backends.cache"
        # SESSION_CACHE_ALIAS = "default"
        # NOTA: Comentado porque puede causar problemas de login si Redis falla
        # Usar sesiones en BD es más confiable
    else:
        raise redis.ConnectionError("Redis no disponible")

except (ImportError, redis.ConnectionError, redis.TimeoutError, Exception) as e:
    # Si Redis no está instalado o no está corriendo, usar cache en memoria local
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'censo-cache',
            'TIMEOUT': 300,
        }
    }
    import sys
    # Usar print sin emojis para evitar problemas de codificación en Windows
    sys.stderr.write("WARNING: Redis no disponible. Usando cache en memoria local (temporal).\n")
    sys.stderr.write("NOTA: Para mejor performance, instala y ejecuta Redis\n")
    sys.stderr.write("Ver: INSTALACION_REDIS.md\n")

# Usar sesiones en base de datos (más confiable que cache)
# Esto evita problemas de login cuando Redis no está disponible
SESSION_ENGINE = "django.contrib.sessions.backends.db"


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 12,  # Mínimo 12 caracteres
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Políticas adicionales de contraseñas
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',  # Más seguro
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

# Expiración de contraseñas (opcional - descomentar si se requiere)
# PASSWORD_EXPIRY_DAYS = 90
# PASSWORD_RESET_TIMEOUT = 86400  # 24 horas (por defecto en Django 6.0)


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es-co'
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# STATICFILES_DIRS = (BASE_DIR / 'static')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


# 'DIRS': [BASE_DIR / 'templates'],

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==============================================================================
# EMAIL CONFIGURATION
# ==============================================================================

# Obtener configuración desde .env
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER)
SERVER_EMAIL = config('SERVER_EMAIL', default=EMAIL_HOST_USER)

# Email timeout y retry
EMAIL_TIMEOUT = 10  # 10 segundos

# Para desarrollo, puedes descomentar la siguiente línea para ver emails en consola:
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# MEDIA

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Sesion
USERSESSIONS_TRACK_ACTIVITY = False


# CORS
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:5173',
    cast=Csv()
)
CORS_ALLOW_CREDENTIALS = True

# NO usar CORS_ORIGIN_ALLOW_ALL = True en producción (inseguro)

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "rest_framework.schemas.coreapi.AutoSchema",
    # Rate limiting para prevenir abuso de API
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',      # Anónimos: 100 requests por día
        'user': '1000/day',     # Autenticados: 1000 requests por día
    },
    # Autenticación - JWT habilitado
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    # Permisos por defecto
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Paginación
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    # Renderizadores - Solo JSON y Browsable API (sin filtros HTML)
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    # Template para filtros - COMENTADO TEMPORALMENTE POR INCOMPATIBILIDAD
    # 'DEFAULT_FILTER_BACKENDS': [
    #     'django_filters.rest_framework.DjangoFilterBackend',
    # ],
}

# ==============================================================================
# SIMPLE JWT SETTINGS
# ==============================================================================

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',
}


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': config('LOG_LEVEL', default='INFO'),
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'maxBytes': 1024 * 1024 * 15,  # 15MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'security.log'),
            'maxBytes': 1024 * 1024 * 15,  # 15MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['security_file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'censoapp': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['file', 'console'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}

# ==============================================================================
# SENTRY - ERROR MONITORING
# ==============================================================================

if not DEBUG:
    # Solo activar Sentry en producción
    sentry_dsn = config('SENTRY_DSN', default='')
    if sentry_dsn:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration

        sentry_sdk.init(
            dsn=sentry_dsn,
            integrations=[DjangoIntegration()],

            # Tasa de muestreo de performance (1.0 = 100%, 0.1 = 10%)
            traces_sample_rate=0.1,

            # Entorno (development, staging, production)
            environment=config('SENTRY_ENVIRONMENT', default='production'),

            # NO enviar información personal de usuarios
            send_default_pii=False,

            # Capturar errores de base de datos
            _experiments={
                "profiles_sample_rate": 0.1,
            },
        )
        print("✅ Sentry inicializado para monitoreo de errores")

# ==============================================================================
# ADMIN EMAIL NOTIFICATIONS
# ==============================================================================

# Notificaciones por email en caso de errores 500 en producción
if not DEBUG:
    ADMINS = [
        ('Admin', config('ADMIN_EMAIL', default='')),
    ]
    MANAGERS = ADMINS
    SERVER_EMAIL = config('SERVER_EMAIL', default='no-reply@censo.com')

# ==============================================================================
# SECURITY MIDDLEWARE CONFIGURATION
# ==============================================================================

# Crear directorio de logs si no existe
import pathlib
pathlib.Path(os.path.join(BASE_DIR, 'logs')).mkdir(exist_ok=True)

# ==============================================================================
# LEAFLET MAPS CONFIGURATION
# ==============================================================================

LEAFLET_CONFIG = {
    # Configuración del mapa base
    'DEFAULT_CENTER': (4.5709, -74.2973),  # Coordenadas Colombia (Bogotá)
    'DEFAULT_ZOOM': 6,
    'MIN_ZOOM': 3,
    'MAX_ZOOM': 18,

    # Capas de tiles (OpenStreetMap)
    'TILES': [
        ('OpenStreetMap',
         'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
         {'attribution': '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',
          'maxZoom': 19}),
        ('Satellite',
         'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
         {'attribution': 'Tiles &copy; Esri',
          'maxZoom': 19}),
        ('Topo',
         'https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',
         {'attribution': 'Map data: &copy; OpenStreetMap, SRTM | Map style: &copy; OpenTopoMap',
          'maxZoom': 17}),
    ],

    # Escala y controles
    'SCALE': 'both',  # metric, imperial o both
    'ATTRIBUTION_PREFIX': 'Censo Web',

    # Plugins
    'PLUGINS': {
        'forms': {
            'auto-include': True
        },
        'draw': {
            'css': ['https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.4/leaflet.draw.css'],
            'js': 'https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.4/leaflet.draw.js',
            'auto-include': True,
        },
        'markercluster': {
            'css': ['https://unpkg.com/leaflet.markercluster@1.4.1/dist/MarkerCluster.css',
                    'https://unpkg.com/leaflet.markercluster@1.4.1/dist/MarkerCluster.Default.css'],
            'js': 'https://unpkg.com/leaflet.markercluster@1.4.1/dist/leaflet.markercluster.js',
            'auto-include': True,
        },
    },

    # Límites espaciales (opcional)
    'SPATIAL_EXTENT': (-85.0, -180.0, 85.0, 180.0),  # (south, west, north, east)

    # Overlays (capas adicionales)
    'OVERLAYS': [],

    # Reset view
    'RESET_VIEW': True,
}

