# Generated by Django 4.2.7 on 2024-02-01 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association_name', models.CharField(max_length=50)),
                ('association_identification', models.CharField(max_length=15)),
                ('association_type_document', models.CharField(default='NIT', help_text='Ingrese NIT', max_length=3)),
                ('association_phone_mobile', models.CharField(help_text='Ingrese número de celular', max_length=15)),
                ('association_phone', models.CharField(max_length=15)),
                ('association_address', models.CharField(max_length=50)),
                ('association_departament', models.CharField(help_text='Registre el departamento', max_length=15)),
                ('association_email', models.EmailField(max_length=254)),
                ('association_logo', models.ImageField(null=True, upload_to='Association')),
            ],
        ),
        migrations.CreateModel(
            name='CivilState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_state_civil', models.CharField(max_length=1)),
                ('state_civil', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_document_type', models.CharField(max_length=3, unique=True)),
                ('document_type', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_education_level', models.CharField(max_length=1)),
                ('education_level', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_eps', models.CharField(max_length=6, unique=True)),
                ('name_eps', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_home', models.CharField(help_text='Registre donde vive la familia', max_length=50, verbose_name='Dirección Vivienda')),
                ('latitude', models.CharField(default='0', help_text='Registre la latitud', max_length=15, verbose_name='Latitud')),
                ('longitude', models.CharField(default='0', help_text='Registre la longitud', max_length=15, verbose_name='Longitud')),
                ('zone', models.CharField(choices=[('R', 'Rural'), ('U', 'Urbana')], help_text='Seleccione Urbana o Rural', max_length=1, verbose_name='Zona')),
                ('family_card_number', models.IntegerField(default=0, unique=True, verbose_name='Número de Familia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Última Actualización')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_code', models.CharField(max_length=1)),
                ('gender', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Kinship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_kinship', models.CharField(max_length=1)),
                ('description_kinship', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Occupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_occupancy', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=50)),
                ('organization_identification', models.CharField(max_length=15, unique=True)),
                ('organization_type_identification', models.CharField(default='NIT', max_length=3)),
                ('organization_territory', models.CharField(max_length=50)),
                ('organization_email', models.EmailField(max_length=254)),
                ('organization_mobile_phone', models.CharField(max_length=15)),
                ('organization_phone', models.CharField(max_length=15)),
                ('organization_address', models.CharField(max_length=50)),
                ('organization_logo', models.ImageField(upload_to='Images')),
                ('association_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censoapp.association')),
            ],
        ),
        migrations.CreateModel(
            name='SecuritySocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_security_social', models.CharField(max_length=5, unique=True)),
                ('affiliation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sidewalks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sidewalk_name', models.CharField(max_length=40)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censoapp.organizations')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_1', models.CharField(max_length=30, verbose_name='Primer Nombre')),
                ('first_name_2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Nombre')),
                ('last_name_1', models.CharField(max_length=30, verbose_name='Primer Apellido')),
                ('last_name_2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Apellido')),
                ('identification_person', models.CharField(max_length=15, unique=True, verbose_name='Identificación')),
                ('cell_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono Móvil')),
                ('personal_email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Correo Personal')),
                ('date_birth', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('handicap', models.CharField(choices=[('1', 'Discapacidad Física'), ('2', 'Discapacidad Auditiva'), ('3', 'Discapacidad Visual'), ('4', 'Sordoceguera'), ('5', 'Discapacidad intelectual'), ('6', 'Discapacidad psicosocial'), ('7', 'Ninguna')], default='Ninguna', max_length=50, verbose_name='Capacidades Diversas')),
                ('civil_state', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='censoapp.civilstate', verbose_name='Estado Civil')),
                ('document_type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='censoapp.documenttype', verbose_name='Tipo de documento')),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censoapp.educationlevel', verbose_name='Nivel Educativo')),
                ('eps', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='censoapp.eps', verbose_name='EPS')),
                ('family_card', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='censoapp.familycard', verbose_name='Familia')),
                ('gender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censoapp.gender', verbose_name='Género')),
                ('kinship_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censoapp.kinship', verbose_name='Parentescos')),
                ('occupation', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='censoapp.occupancy', verbose_name='Ocupación')),
                ('social_insurance', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='censoapp.securitysocial', verbose_name='Seguridad Social')),
            ],
        ),
        migrations.AddField(
            model_name='familycard',
            name='organization_id',
            field=models.ForeignKey(default='', help_text='Seleccione el Resguardo', on_delete=django.db.models.deletion.CASCADE, to='censoapp.organizations', verbose_name='Resguardo'),
        ),
        migrations.AddField(
            model_name='familycard',
            name='sidewalk_home',
            field=models.ForeignKey(help_text='Seleccione la vereda donde vive', on_delete=django.db.models.deletion.CASCADE, to='censoapp.sidewalks', verbose_name='Vereda'),
        ),
    ]
