# Generated by Django 4.2.7 on 2024-01-27 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='document_type',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='familycard',
            name='latitude',
            field=models.CharField(default='0', help_text='Registre la latitud', max_length=15),
        ),
        migrations.AlterField(
            model_name='familycard',
            name='longitude',
            field=models.CharField(default='0', help_text='Registre la longitud', max_length=15),
        ),
        migrations.AlterField(
            model_name='familycard',
            name='zone',
            field=models.CharField(choices=[('R', 'Rural'), ('U', 'Urbana')], help_text='Seleccione la zona', max_length=1),
        ),
        migrations.AlterField(
            model_name='kinship',
            name='description_kinship',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='occupancy',
            name='description_occupancy',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='sidewalks',
            name='sidewalk_name',
            field=models.CharField(max_length=40),
        ),
    ]
