# Generated by Django 4.2.7 on 2024-03-07 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('censoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='civil_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censoapp.civilstate', verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='person',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censoapp.documenttype', verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='person',
            name='eps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censoapp.eps', verbose_name='EPS'),
        ),
        migrations.AlterField(
            model_name='person',
            name='handicap',
            field=models.CharField(choices=[('1', 'Discapacidad Física'), ('2', 'Discapacidad Auditiva'), ('3', 'Discapacidad Visual'), ('4', 'Sordoceguera'), ('5', 'Discapacidad intelectual'), ('6', 'Discapacidad psicosocial'), ('7', 'Ninguna')], max_length=50, verbose_name='Capacidades Diversas'),
        ),
        migrations.AlterField(
            model_name='person',
            name='occupation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censoapp.occupancy', verbose_name='Ocupación'),
        ),
    ]
