# Generated by Django 4.2.7 on 2024-02-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='family_head',
            field=models.BooleanField(default=False, verbose_name='Cabeza de Familia'),
        ),
    ]
