# Generated by Django 4.2.7 on 2024-01-22 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('censoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='occupation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='censoapp.occupancy', verbose_name='Ocupación'),
        ),
    ]
