# Generated by Django 4.2.7 on 2024-01-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Association',
            name='association_logo',
            field=models.ImageField(null=True, upload_to='Association'),
        ),
    ]
