# Generated by Django 4.2.7 on 2024-10-23 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('censoapp', '0002_handicap_alter_familycard_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familycard',
            name='address_home',
            field=models.CharField(blank=True, help_text='Registre donde vive la familia', max_length=50, null=True, verbose_name='Dirección Vivienda'),
        ),
        migrations.AlterField(
            model_name='familycard',
            name='sidewalk_home',
            field=models.ForeignKey(blank=True, help_text='Seleccione la vereda donde vive', null=True, on_delete=django.db.models.deletion.CASCADE, to='censoapp.sidewalks', verbose_name='Vereda'),
        ),
    ]
