# Generated by Django 4.2.7 on 2024-06-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censoapp', '0002_alter_person_civil_state_alter_person_document_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handicap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_handicap', models.CharField(max_length=1)),
                ('handicap', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='familycard',
            options={'ordering': ['family_card_number']},
        ),
        migrations.AlterField(
            model_name='association',
            name='association_logo',
            field=models.ImageField(null=True, upload_to='Association', verbose_name='Logo Association'),
        ),
        migrations.AlterField(
            model_name='familycard',
            name='zone',
            field=models.CharField(choices=[('', 'Seleccione la zona'), ('Rural', 'Rural'), ('Urbana', 'Urbana')], help_text='Seleccione Urbana o Rural', max_length=10, verbose_name='Zona'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='organization_logo',
            field=models.ImageField(upload_to='Images', verbose_name='Logo Organization'),
        ),
    ]
