# Generated by Django 4.2.7 on 2024-01-29 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('censoapp', '0002_alter_documenttype_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='document_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='censoapp.documenttype', verbose_name='Tipo de documento'),
        ),
        migrations.AddField(
            model_name='person',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Correo Personal'),
        ),
        migrations.AlterField(
            model_name='familycard',
            name='address_home',
            field=models.CharField(help_text='Registre donde vive la familia', max_length=50, verbose_name='Dirección Vivienda'),
        ),
        migrations.AlterField(
            model_name='familycard',
            name='latitude',
            field=models.CharField(default='0', help_text='Registre la latitud', max_length=15, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='familycard',
            name='longitude',
            field=models.CharField(default='0', help_text='Registre la longitud', max_length=15, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='familycard',
            name='organization_id',
            field=models.ForeignKey(default='', help_text='Seleccione el Resguardo', on_delete=django.db.models.deletion.CASCADE, to='censoapp.organizations', verbose_name='Resguardo'),
        ),
        migrations.AlterField(
            model_name='familycard',
            name='sidewalk_home',
            field=models.ForeignKey(help_text='Seleccione la vereda donde vive', on_delete=django.db.models.deletion.CASCADE, to='censoapp.sidewalks', verbose_name='Vereda'),
        ),
        migrations.AlterField(
            model_name='familycard',
            name='zone',
            field=models.CharField(choices=[('R', 'Rural'), ('U', 'Urbana')], help_text='Seleccione Urbana o Rural', max_length=1, verbose_name='Zona'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono Móvil'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_birth',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='person',
            name='education_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censoapp.educationlevel', verbose_name='Nivel Educativo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name_1',
            field=models.CharField(max_length=30, verbose_name='Primer Nombre'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name_2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Nombre'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censoapp.gender', verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='person',
            name='handicap',
            field=models.CharField(choices=[('1', 'Discapacidad Física'), ('2', 'Discapacidad Auditiva'), ('3', 'Discapacidad Visual'), ('4', 'Sordoceguera'), ('5', 'Discapacidad intelectual'), ('6', 'Discapacidad psicosocial'), ('7', 'Ninguna')], default='Ninguna', max_length=50, verbose_name='Capacidades Diversas'),
        ),
        migrations.AlterField(
            model_name='person',
            name='identification_person',
            field=models.CharField(max_length=15, unique=True, verbose_name='Identificación'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name_1',
            field=models.CharField(max_length=30, verbose_name='Primer Apellido'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name_2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Apellido'),
        ),
    ]
