# Generated by Django 4.2.7 on 2024-01-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censoapp', '0002_alter_association_association_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='association_logo',
            field=models.ImageField(null=True, upload_to='Association'),
        ),
    ]
