# Generated by Django 4.2.7 on 2024-01-27 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('censoapp', '0002_alter_documenttype_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='education_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censoapp.educationlevel'),
        ),
    ]
