# Generated by Django 4.2.7 on 2024-10-26 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('censoapp', '0003_alter_familycard_address_home_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familycard',
            old_name='organization_id',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='gender_id',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='kinship_id',
            new_name='kinship',
        ),
    ]
