# Generated by Django 4.2.7 on 2024-01-22 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('censoapp', '0003_alter_association_association_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='familycard',
            name='organization_id',
            field=models.ForeignKey(default='', help_text='Seleccione la organización', on_delete=django.db.models.deletion.CASCADE, to='censoapp.organizations'),
        ),
        migrations.AddField(
            model_name='person',
            name='civil_state',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='censoapp.civilstate', verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='person',
            name='education_level',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='censoapp.educationlevel', verbose_name='Nivel Educativo'),
        ),
        migrations.AddField(
            model_name='person',
            name='family_card',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='censoapp.familycard', verbose_name='Familia'),
        ),
        migrations.AddField(
            model_name='person',
            name='occupation',
            field=models.CharField(default='', help_text='Registre la ocupación', max_length=50, verbose_name='Ocupación'),
        ),
        migrations.AlterField(
            model_name='civilstate',
            name='state_civil',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='familycard',
            name='latitude',
            field=models.CharField(default=0, help_text='Registre la latitud', max_length=15),
        ),
        migrations.AlterField(
            model_name='familycard',
            name='length',
            field=models.CharField(default=0, help_text='Registre la longitud', max_length=15),
        ),
        migrations.AlterField(
            model_name='familycard',
            name='sidewalk_home',
            field=models.ForeignKey(help_text='Seleccione la vereda', on_delete=django.db.models.deletion.CASCADE, to='censoapp.sidewalks'),
        ),
        migrations.AlterField(
            model_name='familycard',
            name='zone',
            field=models.CharField(choices=[(1, 'Rural'), (2, 'Urbana')], help_text='Seleccione la zona', max_length=1),
        ),
    ]
