# Generated by Django 4.2.7 on 2024-01-30 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('censoapp', '0003_person_document_type_person_personal_email_and_more'),
        ('censoapp', '0003_person_personal_email_alter_person_education_level'),
    ]

    operations = [
    ]
