# Generated by Django 4.2.7 on 2024-10-27 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('censoapp', '0004_rename_organization_id_familycard_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familycard',
            name='sidewalk_home',
            field=models.ForeignKey(blank=True, help_text='Seleccione la vereda donde vive', null=True, on_delete=django.db.models.deletion.CASCADE, to='censoapp.sidewalks', verbose_name='Vereda'),
        ),
        migrations.AlterField(
            model_name='person',
            name='family_card',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='censoapp.familycard', verbose_name='Familia'),
        ),
    ]
