# Generated by Django 4.2.7 on 2025-01-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censoapp', '0005_alter_familycard_sidewalk_home_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familycard',
            name='address_home',
            field=models.CharField(help_text='Registre donde vive la familia', max_length=50, verbose_name='Dirección Vivienda'),
        ),
        migrations.AlterField(
            model_name='person',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Vivo'),
        ),
    ]
