# Generated by Django 4.2.7 on 2025-01-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censoapp', '0006_alter_familycard_address_home_alter_person_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familycard',
            name='address_home',
            field=models.CharField(blank=True, help_text='Registre donde vive la familia', max_length=50, null=True, verbose_name='Dirección Vivienda'),
        ),
    ]
