# Generated by Django 4.2.7 on 2025-01-11 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('censoapp', '0007_alter_familycard_address_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familycard',
            name='sidewalk_home',
            field=models.ForeignKey(default=1, help_text='Seleccione la vereda donde vive', on_delete=django.db.models.deletion.CASCADE, to='censoapp.sidewalks', verbose_name='Vereda'),
            preserve_default=False,
        ),
    ]
