# Generated by Django 4.2.7 on 2025-06-02 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('censoapp', '0008_alter_familycard_sidewalk_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='handicap',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='censoapp.handicap', verbose_name='Capacidades Diversas'),
        ),
    ]
