# Generated by Django 4.2.7 on 2025-06-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censoapp', '0009_alter_person_handicap'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=250)),
            ],
        ),
    ]
