# Generated by Django 4.2.7 on 2025-06-22 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('censoapp', '0010_systemparameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='family_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censoapp.familycard', verbose_name='Ficha Familiar'),
        ),
    ]
