# Generated by Django 4.2.7 on 2025-06-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censoapp', '0011_alter_person_family_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_name', models.CharField(max_length=150, unique=True)),
                ('authorized_sign', models.BooleanField(default=False, help_text='¿Esta persona está autorizada para firmar documentos?')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
    ]
