# Generated by Django 4.2.7 on 2025-06-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censoapp', '0012_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='familycard',
            name='state',
            field=models.BooleanField(default=True, help_text='¿La ficha familiar está activa?', verbose_name='Estado de la Ficha'),
        ),
        migrations.AlterField(
            model_name='familycard',
            name='address_home',
            field=models.CharField(blank=True, help_text='Registre Información Adicional', max_length=50, null=True, verbose_name='Dirección Vivienda'),
        ),
    ]
