# Generated by Django 4.2.7 on 2025-07-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censoapp', '0013_familycard_state_alter_familycard_address_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialConstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=50, unique=True)),
                ('roof', models.BooleanField(default=False, help_text='¿El material es utilizado en techos?')),
                ('wall', models.BooleanField(default=False, help_text='¿El material es utilizado en paredes?')),
                ('floor', models.BooleanField(default=False, help_text='¿El material es utilizado en pisos?')),
            ],
            options={
                'verbose_name': 'Material de Construcción',
                'verbose_name_plural': 'Materiales de Construcción',
                'ordering': ['material_name'],
            },
        ),
    ]
