# Generated by Django 4.2.7 on 2025-08-02 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('censoapp', '0014_materialconstruction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookingFuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Combustible',
                'verbose_name_plural': 'Tipos de Combustible',
            },
        ),
        migrations.CreateModel(
            name='HomeOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_type', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Propiedad',
                'verbose_name_plural': 'Tipos de Propiedad',
            },
        ),
        migrations.CreateModel(
            name='LightingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lighting_type', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Iluminación',
                'verbose_name_plural': 'Tipos de Iluminación',
            },
        ),
        migrations.CreateModel(
            name='WasteManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_type', models.CharField(max_length=50, unique=True)),
                ('biodegradable', models.BooleanField(default=False, help_text='¿El residuo es biodegradable?')),
                ('recyclable', models.BooleanField(default=False, help_text='¿El residuo es reciclable?')),
                ('non_recyclable', models.BooleanField(default=False, help_text='¿El residuo no es reciclable?')),
                ('hazardous', models.BooleanField(default=False, help_text='¿El residuo es peligroso?')),
                ('excreta', models.BooleanField(default=False, help_text='¿El residuo es excreta?')),
                ('wastewater', models.BooleanField(default=False, help_text='¿El residuo es agua?')),
            ],
            options={
                'verbose_name': 'Tipo de Manejo de Residuos',
                'verbose_name_plural': 'Tipos de Manejo de Residuos',
            },
        ),
        migrations.CreateModel(
            name='WaterSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Fuente de Agua',
                'verbose_name_plural': 'Fuentes de Agua',
            },
        ),
        migrations.CreateModel(
            name='WaterTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Tratamiento de Agua',
                'verbose_name_plural': 'Tipos de Tratamiento de Agua',
            },
        ),
        migrations.CreateModel(
            name='PublicServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_service', models.BooleanField(default=False, help_text='¿La vivienda cuenta con servicio de agua?', verbose_name='Servicio de Agua')),
                ('electricity_service', models.BooleanField(default=False, help_text='¿La vivienda cuenta con servicio de electricidad?', verbose_name='Servicio de Electricidad')),
                ('sewage_service', models.BooleanField(default=False, help_text='¿La vivienda cuenta con servicio de alcantarillado?', verbose_name='Servicio de Alcantarillado')),
                ('internet_service', models.BooleanField(default=False, help_text='¿La vivienda cuenta con servicio de internet?', verbose_name='Servicio de Internet')),
                ('biodegradable_waste', models.ForeignKey(help_text='Seleccione el tipo de manejo de residuos biodegradables', on_delete=django.db.models.deletion.CASCADE, related_name='biodegradable_waste', to='censoapp.wastemanagement', verbose_name='Residuos Biodegradables')),
                ('excreta_waste', models.ForeignKey(help_text='Seleccione el tipo de manejo de excreta', on_delete=django.db.models.deletion.CASCADE, related_name='excreta_waste', to='censoapp.wastemanagement', verbose_name='Excreta')),
                ('family_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censoapp.familycard', verbose_name='Ficha Familiar')),
                ('hazardous_waste', models.ForeignKey(help_text='Seleccione el tipo de manejo de residuos peligrosos', on_delete=django.db.models.deletion.CASCADE, related_name='hazardous_waste', to='censoapp.wastemanagement', verbose_name='Residuos Peligrosos')),
                ('non_recyclable_waste', models.ForeignKey(help_text='Seleccione el tipo de manejo de residuos no reciclables', on_delete=django.db.models.deletion.CASCADE, related_name='non_recyclable_waste', to='censoapp.wastemanagement', verbose_name='Residuos No Reciclables')),
                ('recyclable_waste', models.ForeignKey(help_text='Seleccione el tipo de manejo de residuos reciclables', on_delete=django.db.models.deletion.CASCADE, related_name='recyclable_waste', to='censoapp.wastemanagement', verbose_name='Residuos Reciclables')),
                ('waste_water', models.ForeignKey(help_text='Seleccione el tipo de manejo de aguas residuales', on_delete=django.db.models.deletion.CASCADE, related_name='waste_water', to='censoapp.wastemanagement', verbose_name='Aguas Residuales')),
                ('water_source', models.ForeignKey(help_text='Seleccione la fuente de agua utilizada en la vivienda', on_delete=django.db.models.deletion.CASCADE, to='censoapp.watersource', verbose_name='Fuente de Agua')),
                ('water_treatment', models.ForeignKey(help_text='Seleccione el tipo de tratamiento de agua utilizado en la vivienda', on_delete=django.db.models.deletion.CASCADE, to='censoapp.watertreatment', verbose_name='Tratamiento de Agua')),
            ],
            options={
                'verbose_name': 'Servicios Públicos',
                'verbose_name_plural': 'Servicios Públicos',
                'unique_together': {('family_card',)},
            },
        ),
        migrations.CreateModel(
            name='MaterialConstructionFamilyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_families', models.IntegerField(default=1, verbose_name='Número de Familias')),
                ('number_people_bedrooms', models.IntegerField(default=1, verbose_name='Número de Personas por Habitación')),
                ('condition_roof', models.CharField(max_length=50, verbose_name='Condición del Techo')),
                ('condition_wall', models.CharField(max_length=50, verbose_name='Condición de la Pared')),
                ('condition_floor', models.CharField(max_length=50, verbose_name='Condición del Piso')),
                ('kitchen_location', models.IntegerField(default=1, verbose_name='Ubicación de la Cocina')),
                ('home_smoke', models.BooleanField(default=False, help_text='¿La vivienda tiene problemas de humo?', verbose_name='Humo en la Vivienda')),
                ('number_bedrooms', models.IntegerField(default=1, verbose_name='Número de Habitaciones')),
                ('ventilation', models.BooleanField(default=False, help_text='¿La vivienda cuenta con ventilación adecuada?', verbose_name='Ventilación')),
                ('lighting', models.BooleanField(default=False, help_text='¿La vivienda cuenta con iluminación adecuada?', verbose_name='Iluminación')),
                ('cooking_fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censoapp.cookingfuel', verbose_name='Tipo de Combustible de Cocina')),
                ('family_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censoapp.familycard', verbose_name='Ficha Familiar')),
                ('home_ownership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censoapp.homeownership', verbose_name='Tipo de Propiedad')),
                ('material_floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_materials', to='censoapp.materialconstruction', verbose_name='Material de Piso')),
                ('material_roof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roof_materials', to='censoapp.materialconstruction', verbose_name='Material de Techo')),
                ('material_wall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wall_materials', to='censoapp.materialconstruction', verbose_name='Material de Pared')),
            ],
            options={
                'verbose_name': 'Material de Construcción de Vivienda Familiar',
                'verbose_name_plural': 'Materiales de Construcción de Viviendas Familiares',
                'unique_together': {('family_card', 'material_roof', 'material_wall', 'material_floor')},
            },
        ),
    ]
