# Generated by Django 4.2.7 on 2025-11-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censoapp', '0015_cookingfuel_homeownership_lightingtype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charge',
            options={},
        ),
        migrations.RemoveField(
            model_name='charge',
            name='authorized_sign',
        ),
        migrations.AddField(
            model_name='charge',
            name='main_charge',
            field=models.BooleanField(default=False, help_text='¿Este es el cargo principal?', verbose_name='Cargo Principal'),
        ),
        migrations.AddField(
            model_name='charge',
            name='signature',
            field=models.BooleanField(default=False, help_text='¿Este cargo está autorizado para firmar documentos?', verbose_name='Firma Autorizada'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='charge_name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre del Charge'),
        ),
    ]
