# Generated by Django 4.2.7 on 2025-11-23 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('censoapp', '0016_alter_charge_options_remove_charge_authorized_sign_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charge',
            options={'ordering': ['charge_name'], 'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
    ]
