# Generated by Django 4.2.7 on 2025-11-23 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censoapp', '0017_alter_charge_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charge',
            options={'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.RemoveField(
            model_name='charge',
            name='signature',
        ),
        migrations.AddField(
            model_name='charge',
            name='authorized_sign',
            field=models.BooleanField(default=False, help_text='¿Esta persona está autorizada para firmar documentos?'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='charge_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='main_charge',
            field=models.BooleanField(default=False, help_text='¿Este es el cargo principal?'),
        ),
    ]
