# Generated by Django 4.2.7 on 2025-11-23 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('censoapp', '0018_alter_charge_options_remove_charge_signature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvalGenerated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(verbose_name='Detalle del Aval')),
                ('date_valid', models.DateField(verbose_name='Fecha de Vencimiento del Aval')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censoapp.organizations', verbose_name='Organización')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censoapp.person', verbose_name='Persona Aval')),
            ],
        ),
    ]
