# Generated by Django 4.2.7 on 2025-12-14 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('censoapp', '0019_avalgenerated'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materialconstructionfamilycard',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='materialconstructionfamilycard',
            name='family_card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='material_construction', to='censoapp.familycard', verbose_name='Ficha Familiar'),
        ),
        migrations.AlterModelTable(
            name='materialconstructionfamilycard',
            table='censoapp_materialconstructionfamilycard',
        ),
    ]
