# Generated by Django 4.2.7 on 2025-12-14 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('censoapp', '0020_alter_materialconstructionfamilycard_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPerson',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('first_name_1', models.CharField(max_length=30, verbose_name='Primer Nombre')),
                ('first_name_2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Nombre')),
                ('last_name_1', models.CharField(max_length=30, verbose_name='Primer Apellido')),
                ('last_name_2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Apellido')),
                ('identification_person', models.CharField(db_index=True, max_length=15, verbose_name='Identificación')),
                ('cell_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono Móvil')),
                ('personal_email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Correo Personal')),
                ('date_birth', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('family_head', models.BooleanField(default=False, verbose_name='Cabeza de Familia')),
                ('state', models.BooleanField(default=True, verbose_name='Vivo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('civil_state', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='censoapp.civilstate', verbose_name='Estado Civil')),
                ('document_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='censoapp.documenttype', verbose_name='Tipo de documento')),
                ('education_level', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='censoapp.educationlevel', verbose_name='Nivel Educativo')),
                ('eps', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='censoapp.eps', verbose_name='EPS')),
                ('family_card', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='censoapp.familycard', verbose_name='Ficha Familiar')),
                ('gender', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='censoapp.gender', verbose_name='Género')),
                ('handicap', models.ForeignKey(blank=True, db_constraint=False, max_length=50, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='censoapp.handicap', verbose_name='Capacidades Diversas')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kinship', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='censoapp.kinship', verbose_name='Parentescos')),
                ('occupation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='censoapp.occupancy', verbose_name='Ocupación')),
                ('social_insurance', models.ForeignKey(blank=True, db_constraint=False, max_length=50, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='censoapp.securitysocial', verbose_name='Seguridad Social')),
            ],
            options={
                'verbose_name': 'historical person',
                'verbose_name_plural': 'historical persons',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMaterialConstructionFamilyCard',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('number_families', models.IntegerField(default=1, verbose_name='Número de Familias')),
                ('number_people_bedrooms', models.IntegerField(default=1, verbose_name='Número de Personas por Habitación')),
                ('condition_roof', models.CharField(max_length=50, verbose_name='Condición del Techo')),
                ('condition_wall', models.CharField(max_length=50, verbose_name='Condición de la Pared')),
                ('condition_floor', models.CharField(max_length=50, verbose_name='Condición del Piso')),
                ('kitchen_location', models.IntegerField(default=1, verbose_name='Ubicación de la Cocina')),
                ('home_smoke', models.BooleanField(default=False, help_text='¿La vivienda tiene problemas de humo?', verbose_name='Humo en la Vivienda')),
                ('number_bedrooms', models.IntegerField(default=1, verbose_name='Número de Habitaciones')),
                ('ventilation', models.BooleanField(default=False, help_text='¿La vivienda cuenta con ventilación adecuada?', verbose_name='Ventilación')),
                ('lighting', models.BooleanField(default=False, help_text='¿La vivienda cuenta con iluminación adecuada?', verbose_name='Iluminación')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cooking_fuel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='censoapp.cookingfuel', verbose_name='Tipo de Combustible de Cocina')),
                ('family_card', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='censoapp.familycard', verbose_name='Ficha Familiar')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('home_ownership', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='censoapp.homeownership', verbose_name='Tipo de Propiedad')),
                ('material_floor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='censoapp.materialconstruction', verbose_name='Material de Piso')),
                ('material_roof', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='censoapp.materialconstruction', verbose_name='Material de Techo')),
                ('material_wall', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='censoapp.materialconstruction', verbose_name='Material de Pared')),
            ],
            options={
                'verbose_name': 'historical Material de Construcción de Vivienda Familiar',
                'verbose_name_plural': 'historical Materiales de Construcción de Viviendas Familiares',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFamilyCard',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('address_home', models.CharField(blank=True, help_text='Registre Información Adicional', max_length=50, null=True, verbose_name='Dirección Vivienda')),
                ('latitude', models.CharField(default='0', help_text='Registre la latitud', max_length=15, verbose_name='Latitud')),
                ('longitude', models.CharField(default='0', help_text='Registre la longitud', max_length=15, verbose_name='Longitud')),
                ('zone', models.CharField(choices=[('', 'Seleccione la zona'), ('Rural', 'Rural'), ('Urbana', 'Urbana')], help_text='Seleccione Urbana o Rural', max_length=10, verbose_name='Zona')),
                ('family_card_number', models.IntegerField(db_index=True, default=0, verbose_name='Número de Familia')),
                ('state', models.BooleanField(default=True, help_text='¿La ficha familiar está activa?', verbose_name='Estado de la Ficha')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Última Actualización')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, default='', help_text='Seleccione el Resguardo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='censoapp.organizations', verbose_name='Resguardo')),
                ('sidewalk_home', models.ForeignKey(blank=True, db_constraint=False, help_text='Seleccione la vereda donde vive', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='censoapp.sidewalks', verbose_name='Vereda')),
            ],
            options={
                'verbose_name': 'historical family card',
                'verbose_name_plural': 'historical family cards',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
