# Generated by Django 4.2.7 on 2025-12-14 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('censoapp', '0021_historicalperson_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador de Organizacion'), ('OPERATOR', 'Operador'), ('VIEWER', 'Solo Consulta')], default='OPERATOR', max_length=50, verbose_name='Rol')),
                ('can_view_all_organizations', models.BooleanField(default=False, help_text='Solo para administradores de la asociacion. Permite ver datos de todas las organizaciones.', verbose_name='Acceso a todas las organizaciones')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el perfil esta activo', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('organization', models.ForeignKey(help_text='Organizacion a la que pertenece el usuario', on_delete=django.db.models.deletion.CASCADE, to='censoapp.organizations', verbose_name='Organizacion del Usuario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'ordering': ['user__username'],
            },
        ),
    ]
