# Generated by Django 4.2.7 on 2025-12-14 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('censoapp', '0022_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(choices=[('GOBERNADOR', 'Gobernador'), ('ALCALDE', 'Alcalde'), ('CAPITAN', 'Capitán'), ('ALGUACIL', 'Alguacil'), ('COMISARIO', 'Comisario'), ('TESORERO', 'Tesorero'), ('SECRETARIO', 'Secretario')], help_text='Cargo en la junta directiva', max_length=50, verbose_name='Cargo')),
                ('can_sign_documents', models.BooleanField(default=False, help_text='¿Esta persona está autorizada para firmar documentos oficiales?', verbose_name='Autorizado para Firmar')),
                ('start_date', models.DateField(help_text='Fecha en que inició en el cargo', verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, help_text='Fecha en que finalizó en el cargo (dejar vacío si está activo)', null=True, verbose_name='Fecha de Finalización')),
                ('is_active', models.BooleanField(default=True, help_text='¿El cargo está actualmente activo?', verbose_name='Activo')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Última Actualización')),
                ('alternate_person', models.ForeignKey(blank=True, help_text='Persona que ocupa el cargo como suplente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_position_alternate', to='censoapp.person', verbose_name='Suplente del Cargo')),
                ('holder_person', models.ForeignKey(help_text='Persona que ocupa el cargo como titular', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_position_holder', to='censoapp.person', verbose_name='Titular del Cargo')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_positions', to='censoapp.organizations', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Cargo de Junta Directiva',
                'verbose_name_plural': 'Cargos de Junta Directiva',
                'ordering': ['organization', 'position_name'],
                'unique_together': {('organization', 'position_name', 'is_active')},
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_content', models.TextField(help_text='Contenido completo del documento generado', verbose_name='Contenido del Documento')),
                ('issue_date', models.DateField(help_text='Fecha en que se expide el documento', verbose_name='Fecha de Expedición')),
                ('expiration_date', models.DateField(blank=True, help_text='Fecha de vencimiento del documento (si aplica)', null=True, verbose_name='Fecha de Vencimiento')),
                ('document_number', models.CharField(blank=True, help_text='Número consecutivo del documento', max_length=50, null=True, verbose_name='Número de Documento')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ISSUED', 'Expedido'), ('EXPIRED', 'Vencido'), ('REVOKED', 'Revocado')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Última Actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Documento Generado',
                'verbose_name_plural': 'Documentos Generados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBoardPosition',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('position_name', models.CharField(choices=[('GOBERNADOR', 'Gobernador'), ('ALCALDE', 'Alcalde'), ('CAPITAN', 'Capitán'), ('ALGUACIL', 'Alguacil'), ('COMISARIO', 'Comisario'), ('TESORERO', 'Tesorero'), ('SECRETARIO', 'Secretario')], help_text='Cargo en la junta directiva', max_length=50, verbose_name='Cargo')),
                ('can_sign_documents', models.BooleanField(default=False, help_text='¿Esta persona está autorizada para firmar documentos oficiales?', verbose_name='Autorizado para Firmar')),
                ('start_date', models.DateField(help_text='Fecha en que inició en el cargo', verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, help_text='Fecha en que finalizó en el cargo (dejar vacío si está activo)', null=True, verbose_name='Fecha de Finalización')),
                ('is_active', models.BooleanField(default=True, help_text='¿El cargo está actualmente activo?', verbose_name='Activo')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Última Actualización')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('alternate_person', models.ForeignKey(blank=True, db_constraint=False, help_text='Persona que ocupa el cargo como suplente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='censoapp.person', verbose_name='Suplente del Cargo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('holder_person', models.ForeignKey(blank=True, db_constraint=False, help_text='Persona que ocupa el cargo como titular', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='censoapp.person', verbose_name='Titular del Cargo')),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='censoapp.organizations', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'historical Cargo de Junta Directiva',
                'verbose_name_plural': 'historical Cargos de Junta Directiva',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGeneratedDocument',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('document_content', models.TextField(help_text='Contenido completo del documento generado', verbose_name='Contenido del Documento')),
                ('issue_date', models.DateField(help_text='Fecha en que se expide el documento', verbose_name='Fecha de Expedición')),
                ('expiration_date', models.DateField(blank=True, help_text='Fecha de vencimiento del documento (si aplica)', null=True, verbose_name='Fecha de Vencimiento')),
                ('document_number', models.CharField(blank=True, help_text='Número consecutivo del documento', max_length=50, null=True, verbose_name='Número de Documento')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ISSUED', 'Expedido'), ('EXPIRED', 'Vencido'), ('REVOKED', 'Revocado')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Última Actualización')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'historical Documento Generado',
                'verbose_name_plural': 'historical Documentos Generados',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='IdentificationDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_document_type', models.CharField(max_length=3, unique=True)),
                ('document_type', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Tipo de Documento de Identidad',
                'verbose_name_plural': 'Tipos de Documentos de Identidad',
            },
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ['document_type_name'], 'verbose_name': 'Tipo de Documento', 'verbose_name_plural': 'Tipos de Documentos'},
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='code_document_type',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='document_type',
        ),
        migrations.AddField(
            model_name='documenttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción del tipo de documento', null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='document_type_name',
            field=models.CharField(default='Documento', max_length=100, verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='requires_expiration',
            field=models.BooleanField(default=True, help_text='¿Este tipo de documento tiene fecha de vencimiento?', verbose_name='Requiere Fecha de Vencimiento'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='template_content',
            field=models.TextField(blank=True, help_text='Plantilla base del contenido del documento. Use {variables} para campos dinámicos.', null=True, verbose_name='Plantilla del Documento'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última Actualización'),
        ),
        migrations.DeleteModel(
            name='AvalGenerated',
        ),
        migrations.AddField(
            model_name='historicalgenerateddocument',
            name='document_type',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Tipo de documento a generar (Aval, Constancia, etc.)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='censoapp.documenttype', verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='historicalgenerateddocument',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalgenerateddocument',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Organización que genera y expide el documento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='censoapp.organizations', verbose_name='Organización que Expide'),
        ),
        migrations.AddField(
            model_name='historicalgenerateddocument',
            name='person',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Persona del censo para quien se genera el documento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='censoapp.person', verbose_name='Persona Beneficiaria'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='document_type',
            field=models.ForeignKey(help_text='Tipo de documento a generar (Aval, Constancia, etc.)', on_delete=django.db.models.deletion.CASCADE, to='censoapp.documenttype', verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='organization',
            field=models.ForeignKey(help_text='Organización que genera y expide el documento', on_delete=django.db.models.deletion.CASCADE, to='censoapp.organizations', verbose_name='Organización que Expide'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='person',
            field=models.ForeignKey(help_text='Persona del censo para quien se genera el documento', on_delete=django.db.models.deletion.CASCADE, related_name='documents_received', to='censoapp.person', verbose_name='Persona Beneficiaria'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='signers',
            field=models.ManyToManyField(blank=True, help_text='Miembros de la junta directiva que firman el documento', related_name='signed_documents', to='censoapp.boardposition', verbose_name='Firmantes'),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='document_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='censoapp.identificationdocumenttype', verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='person',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censoapp.identificationdocumenttype', verbose_name='Tipo de documento'),
        ),
    ]
