# Generated by Django 4.2.7 on 2025-12-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censoapp', '0023_boardposition_generateddocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='verification_hash',
            field=models.CharField(blank=True, help_text='Hash único para verificar autenticidad del documento vía código QR', max_length=32, null=True, unique=True, verbose_name='Hash de Verificación'),
        ),
        migrations.AddField(
            model_name='historicalgenerateddocument',
            name='verification_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Hash único para verificar autenticidad del documento vía código QR', max_length=32, null=True, verbose_name='Hash de Verificación'),
        ),
    ]
