# Generated by Django 4.2.7 on 2025-12-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censoapp', '0025_documenttemplate_templateblock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateblock',
            name='config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Configuración del Bloque'),
        ),
        migrations.AlterField(
            model_name='templateblock',
            name='custom_style',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Estilo CSS Personalizado'),
        ),
        migrations.AlterField(
            model_name='templateblock',
            name='font_size_modifier',
            field=models.IntegerField(default=0, help_text='Suma/resta al tamaño base de fuente', verbose_name='Modificador de Tamaño'),
        ),
        migrations.AlterField(
            model_name='templatevariable',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='templatevariable',
            name='variable_name',
            field=models.CharField(help_text="Nombre sin llaves (ej: 'gobernador')", max_length=100, verbose_name='Nombre de la Variable'),
        ),
        migrations.AlterField(
            model_name='templatevariable',
            name='variable_value',
            field=models.TextField(verbose_name='Valor de la Variable'),
        ),
    ]
