# Generated by Django 4.2.7 on 2025-12-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censoapp', '0026_alter_templateblock_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatevariable',
            name='variable_type',
            field=models.CharField(choices=[('static', 'Valor Estático'), ('organization', 'Dato de Organización'), ('person', 'Dato de Persona'), ('family_card', 'Dato de Ficha Familiar')], default='static', help_text='Tipo de variable: estática o dinámica', max_length=20, verbose_name='Tipo de Variable'),
        ),
        migrations.AlterField(
            model_name='templatevariable',
            name='variable_value',
            field=models.TextField(help_text="Para estáticas: el valor directo. Para dinámicas: el campo del modelo (ej: 'organization_territory', 'full_name')", verbose_name='Valor de la Variable'),
        ),
    ]
