# Generated by Django 4.2.7 on 2025-12-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censoapp', '0028_update_templatevariable_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateddocument',
            name='verification_hash',
            field=models.CharField(blank=True, help_text='Hash único para verificar autenticidad del documento vía código QR', max_length=64, null=True, unique=True, verbose_name='Hash de Verificación'),
        ),
        migrations.AlterField(
            model_name='historicalgenerateddocument',
            name='verification_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Hash único para verificar autenticidad del documento vía código QR', max_length=64, null=True, verbose_name='Hash de Verificación'),
        ),
        migrations.AlterField(
            model_name='templatevariable',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción del propósito de esta variable', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='templatevariable',
            name='variable_type',
            field=models.CharField(choices=[('person', 'Dato de Persona'), ('family_card', 'Dato de Ficha Familiar'), ('association', 'Dato de Asociación'), ('organization', 'Dato de Organización')], help_text='Tipo de dato (Persona, Ficha Familiar, Asociación, Organización)', max_length=20, verbose_name='Tipo de Variable'),
        ),
    ]
