# Generated by Django 4.2.7 on 2025-12-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censoapp', '0029_alter_generateddocument_verification_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kinship',
            name='code_kinship',
            field=models.CharField(max_length=2),
        ),
    ]
