# Generated by Django 6.0.1 on 2026-01-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censoapp', '0030_alter_kinship_code_kinship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sidewalks',
            options={'verbose_name': 'Vereda', 'verbose_name_plural': 'Veredas'},
        ),
        migrations.AddField(
            model_name='sidewalks',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción de la vereda', null=True),
        ),
        migrations.AddField(
            model_name='sidewalks',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitud GPS (ej: 2.3167)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sidewalks',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitud GPS (ej: -76.4000)', max_digits=10, null=True),
        ),
    ]
