# Generated by Django 6.0.1 on 2026-02-08 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censoapp', '0031_alter_sidewalks_options_sidewalks_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_email', models.BooleanField(default=True, help_text='Recibir notificaciones por email')),
                ('receive_inapp', models.BooleanField(default=True, help_text='Recibir notificaciones in-app')),
                ('notify_document_expiring', models.BooleanField(default=True, help_text='Notificar documentos por vencer')),
                ('notify_document_expired', models.BooleanField(default=True, help_text='Notificar documentos vencidos')),
                ('notify_document_generated', models.BooleanField(default=False, help_text='Notificar documentos generados')),
                ('notify_person_created', models.BooleanField(default=False, help_text='Notificar nuevas personas')),
                ('notify_family_created', models.BooleanField(default=False, help_text='Notificar nuevas familias')),
                ('notify_system_updates', models.BooleanField(default=True, help_text='Notificar actualizaciones del sistema')),
                ('notify_security_alerts', models.BooleanField(default=True, help_text='Notificar alertas de seguridad')),
                ('email_frequency', models.CharField(choices=[('INSTANT', 'Inmediato'), ('DAILY', 'Diario'), ('WEEKLY', 'Semanal'), ('NEVER', 'Nunca')], default='INSTANT', help_text='Frecuencia de envío de emails', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Usuario', on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de Notificación',
                'verbose_name_plural': 'Preferencias de Notificación',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('DOC_EXP', 'Documento por vencer'), ('DOC_EXPD', 'Documento vencido'), ('DOC_GEN', 'Documento generado'), ('PER_NEW', 'Persona registrada'), ('PER_UPD', 'Persona actualizada'), ('FAM_NEW', 'Familia registrada'), ('FAM_UPD', 'Familia actualizada'), ('SYS_UPD', 'Actualización del sistema'), ('SYS_ERR', 'Error del sistema'), ('SEC_ALT', 'Alerta de seguridad'), ('CUSTOM', 'Personalizada')], default='CUSTOM', help_text='Tipo de notificación', max_length=10)),
                ('title', models.CharField(help_text='Título de la notificación', max_length=200)),
                ('message', models.TextField(help_text='Mensaje de la notificación')),
                ('link', models.CharField(blank=True, help_text='URL para redireccionar (opcional)', max_length=500, null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Indica si la notificación ha sido leída')),
                ('read_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que fue leída', null=True)),
                ('sent_email', models.BooleanField(default=False, help_text='Indica si se envió email')),
                ('email_sent_at', models.DateTimeField(blank=True, help_text='Fecha y hora de envío de email', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última actualización')),
                ('organization', models.ForeignKey(blank=True, help_text='Organización relacionada', null=True, on_delete=django.db.models.deletion.CASCADE, to='censoapp.organizations')),
                ('related_document', models.ForeignKey(blank=True, help_text='Documento relacionado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='censoapp.generateddocument')),
                ('related_family', models.ForeignKey(blank=True, help_text='Ficha familiar relacionada (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='censoapp.familycard')),
                ('related_person', models.ForeignKey(blank=True, help_text='Persona relacionada (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='censoapp.person')),
                ('user', models.ForeignKey(help_text='Usuario que recibe la notificación', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='censoapp_no_user_id_eb2a0c_idx'), models.Index(fields=['user', 'created_at'], name='censoapp_no_user_id_95c7d1_idx'), models.Index(fields=['notification_type'], name='censoapp_no_notific_761892_idx')],
            },
        ),
    ]
