# Generated by Django 6.0.1 on 2026-04-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("censoapp", "0033_loginattempt_passwordresettoken_sessionsecurity_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="association",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Asociación",
                "verbose_name_plural": "Asociaciones",
            },
        ),
        migrations.AddField(
            model_name="association",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Fecha de Creación"
            ),
        ),
        migrations.AddField(
            model_name="association",
            name="founding_date",
            field=models.DateField(blank=True, null=True, verbose_name="Fecha de Fundación"),
        ),
        migrations.AddField(
            model_name="association",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Indica si la asociación está activa",
                verbose_name="Estado Activo",
            ),
        ),
        migrations.AddField(
            model_name="association",
            name="legal_representative",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Representante Legal"
            ),
        ),
        migrations.AddField(
            model_name="association",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Fecha de Actualización"
            ),
        ),
    ]
